import type { Puzzle } from "./types";

const N = 15;
const c = (r: number, col: number) => r * N + col;
const x = (r: number, col: number) => r * 9 + col;
const g = (r: number, col: number) => r * 19 + col;

export const PUZZLES: Puzzle[] = [
  /* ============ CARO — X đi trước, tìm nước mấu chốt ============ */
  { id: "caro-1", game: "caro", title: "Năm quân một đường", difficulty: 1,
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(7, 8)], hint: "Hàng ngang của X sắp đủ 5." },
  { id: "caro-2", game: "caro", title: "Đường chéo ẩn", difficulty: 1,
    setup: { moves: [c(4, 4), c(0, 0), c(5, 5), c(0, 1), c(6, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(8, 8)], hint: "Nhìn đường chéo xuôi từ góc trên." },
  { id: "caro-3", game: "caro", title: "Chặn trước khi muộn", difficulty: 2,
    setup: { moves: [c(3, 3), c(8, 4), c(3, 4), c(8, 5), c(3, 5), c(8, 6), c(3, 6), c(5, 10), c(10, 10)] },
    solution: [c(8, 3)], hint: "O có 4 quân hàng 9 — chặn đầu còn trống mở." },
  { id: "caro-4", game: "caro", title: "Bốn mở hai đầu", difficulty: 1,
    setup: { moves: [c(6, 4), c(0, 0), c(6, 5), c(0, 1), c(6, 6), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(6, 3)], hint: "X có 4 quân hàng 7 — nối đủ 5 là thắng." },
  { id: "caro-5", game: "caro", title: "Chặn đúng một đầu", difficulty: 1,
    setup: { moves: [c(0, 0), c(8, 3), c(0, 1), c(8, 4), c(0, 2), c(8, 5), c(8, 7), c(8, 6)] },
    solution: [c(8, 2)], hint: "O có 4 quân, đầu phải đã bị X bịt — chỉ còn một đầu sống." },
  { id: "caro-6", game: "caro", title: "Chéo lên phải", difficulty: 1,
    setup: { moves: [c(9, 3), c(0, 0), c(8, 4), c(0, 1), c(7, 5), c(0, 2), c(6, 6), c(0, 3)] },
    solution: [c(5, 7)], hint: "Đường chéo đi lên từ trái dưới." },
  { id: "caro-7", game: "caro", title: "Ba đôi ngang dọc", difficulty: 2,
    setup: { moves: [c(7, 5), c(0, 0), c(7, 6), c(0, 1), c(5, 7), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(7, 7)], hint: "Một nước tạo hai hàng ba mở — O không chặn xuể." },
  { id: "caro-8", game: "caro", title: "Phá ba đôi của đối thủ", difficulty: 2,
    setup: { moves: [c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(5, 7), c(0, 3), c(6, 7)] },
    solution: [c(7, 7)], hint: "O sắp đặt (7,7) tạo ba đôi — X chiếm trước giao điểm đó." },
  { id: "caro-9", game: "caro", title: "Thắng cột dọc", difficulty: 1,
    setup: { moves: [c(3, 7), c(2, 7), c(4, 7), c(0, 0), c(5, 7), c(0, 1), c(6, 7), c(0, 2)] },
    solution: [c(7, 7)], hint: "Đầu trên đã bị O bịt — còn đầu dưới." },
  { id: "caro-10", game: "caro", title: "Ba đôi chéo ngang", difficulty: 2,
    setup: { moves: [c(5, 5), c(0, 0), c(6, 6), c(0, 1), c(7, 5), c(0, 2), c(7, 6), c(0, 3)] },
    solution: [c(7, 7)], hint: "Giao điểm (7,7) nối được cả đường chéo lẫn hàng ngang." },

  /* ============ CỜ VUA ============ */
  { id: "chess-1", game: "chess", title: "Chiếu hết hàng cuối", difficulty: 1,
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Vua đen không có ô thoát — đưa hậu xuống đáy." },
  { id: "chess-2", game: "chess", title: "Bẫy học trò", difficulty: 1,
    setup: { fen: "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1" },
    solution: [{ from: "h5", to: "f7" }], hint: "Hậu + tượng cùng nhắm f7 — tốt yếu nhất bàn cờ." },
  { id: "chess-3", game: "chess", title: "Xe chiếu hết hàng cuối", difficulty: 2,
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Đưa xe xuống hàng 8 — vua đen kẹt sau 3 tốt." },
  { id: "chess-4", game: "chess", title: "Hai xe soi hàng", difficulty: 1,
    setup: { fen: "7k/R7/8/8/8/8/8/1R5K w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Xe a7 đã khóa hàng 7 — xe còn lại đặt hàng 8." },
  { id: "chess-5", game: "chess", title: "Xe ăn xe rồi hết", difficulty: 1,
    setup: { fen: "4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Ăn xe e8 — chiếu hết luôn vì hàng 8 không ai thủ." },
  { id: "chess-6", game: "chess", title: "Nĩa mã vua và hậu", difficulty: 2,
    setup: { fen: "6k1/8/8/3q4/4N3/8/8/4K3 w - - 0 1" },
    solution: [{ from: "e4", to: "f6" }], hint: "Mã f6 chiếu vua g8, đồng thời treo hậu d5." },
  { id: "chess-7", game: "chess", title: "Skewer bắt hậu", difficulty: 2,
    setup: { fen: "4k3/4q3/8/8/8/8/8/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e7" }], hint: "Xe ăn hậu e7 chiếu — vua phải đổi xe cho hậu." },
  { id: "chess-8", game: "chess", title: "Hậu c8 kết liễu", difficulty: 2,
    setup: { fen: "6k1/5ppp/8/8/8/7Q/6PP/6K1 w - - 0 1" },
    solution: [{ from: "h3", to: "c8" }], hint: "Hậu xuống hàng 8 — vua bị chính tốt mình chặn." },
  { id: "chess-9", game: "chess", title: "Ăn hậu giữa bàn", difficulty: 1,
    setup: { fen: "4k3/8/8/8/8/8/3q4/3R1K2 w - - 0 1" },
    solution: [{ from: "d1", to: "d2" }], hint: "Hậu đen d2 không ai giữ — xe đứng cạnh ăn ngay." },
  { id: "chess-10", game: "chess", title: "Hậu g7 sát", difficulty: 2,
    setup: { fen: "6k1/5p1p/7P/8/8/8/1Q4P1/6K1 w - - 0 1" },
    solution: [{ from: "b2", to: "g7" }], hint: "Đường chéo b2–g7 mở sẵn; tốt h6 đỡ hậu trên g7." },
  { id: "chess-11", game: "chess", title: "Tượng bắt xe tự do", difficulty: 1,
    setup: { fen: "4k3/8/8/8/3r4/8/8/4K1B1 w - - 0 1" },
    solution: [{ from: "g1", to: "d4" }], hint: "Xe d4 không ai giữ — đường chéo g1–d4 trống." },

  /* ============ CỜ TƯỚNG — đỏ đi trước ============ */
  { id: "xq-1", game: "xiangqi", title: "Pháo ăn mã đầu ván", difficulty: 1,
    setup: { moves: [] },
    solution: [{ from: x(7, 1), to: x(0, 1) }], hint: "Pháo đỏ (7,1) nhảy qua ngòi pháo đen (2,1) để ăn mã." },
  { id: "xq-2", game: "xiangqi", title: "Pháo trung lộ ăn tốt", difficulty: 1,
    setup: { moves: [{ from: x(7, 1), to: x(7, 4) }, { from: x(0, 1), to: x(2, 2) }] },
    solution: [{ from: x(7, 4), to: x(3, 4) }], hint: "Tốt đỏ (6,4) là ngòi — pháo ăn tốt đen giữa sông." },
  { id: "xq-3", game: "xiangqi", title: "Xe đâm thẳng bắt tướng", difficulty: 1,
    setup: { fen: "3aga3/9/9/9/4R4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 4), to: x(0, 4) }], hint: "Cột giữa trống hoàn toàn — xe lên tận bắt tướng." },
  { id: "xq-4", game: "xiangqi", title: "Mã nhảy chiếu hết", difficulty: 2,
    setup: { fen: "3aga3/9/9/9/2H6/4R4/9/9/9/4G4 r" },
    solution: [{ from: x(4, 2), to: x(2, 3) }], hint: "Mã (2,3) chiếu — tướng kẹt giữa hai sĩ, ô (1,4) đã bị xe (5,4) khóa." },
  { id: "xq-5", game: "xiangqi", title: "Pháo bắn xe qua ngòi", difficulty: 1,
    setup: { fen: "r2aga3/9/p8/9/9/C8/9/9/9/3G5 r" },
    solution: [{ from: x(5, 0), to: x(0, 0) }], hint: "Chỉ đúng một quân cản giữa — ngòi pháo hoàn hảo." },
  { id: "xq-6", game: "xiangqi", title: "Mã tẩu ăn pháo", difficulty: 1,
    setup: { fen: "3aga3/9/9/9/2c6/9/1H7/9/9/3G5 r" },
    solution: [{ from: x(6, 1), to: x(4, 2) }], hint: "Chân mã (5,1) trống — nhảy lên ăn pháo." },
  { id: "xq-7", game: "xiangqi", title: "Tốt qua sông ăn mã", difficulty: 1,
    setup: { fen: "3aga3/9/9/9/3Ph4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 3), to: x(4, 4) }], hint: "Tốt đã qua sông được đi ngang — ăn mã ngay." },
  { id: "xq-8", game: "xiangqi", title: "Xe ăn sĩ phá cung", difficulty: 2,
    setup: { fen: "3aga3/3R5/9/9/9/9/9/9/9/3G5 r" },
    solution: [{ from: x(1, 3), to: x(0, 3) }], hint: "Ăn sĩ (0,3) — mở mặt tướng và chiếu luôn." },
  { id: "xq-9", game: "xiangqi", title: "Tốt độc phá sát", difficulty: 2,
    setup: { fen: "3aga3/4P4/9/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(1, 4), to: x(0, 4) }], hint: "Tốt lao xuống bắt tướng — sĩ không cứu được." },
  { id: "xq-10", game: "xiangqi", title: "Mã góc pháo bộ", difficulty: 2,
    setup: { fen: "3aga3/9/5H3/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 5), to: x(0, 4) }], hint: "Mã (2,5) nhảy góc (0,4) — chân mã (1,5) trống." },

  /* ============ CỜ VÂY — đen đi trước, bắt quân ============ */
  { id: "go-1", game: "go", title: "Bắt quân đầu tiên", difficulty: 1,
    setup: { moves: [g(9, 10), g(10, 10), g(10, 9), g(0, 0), g(11, 10), g(0, 1)] },
    solution: [g(10, 11)], hint: "Trắng (10,10) chỉ còn 1 khí." },
  { id: "go-2", game: "go", title: "Bắt nhóm hai quân", difficulty: 2,
    setup: { moves: [g(9, 9), g(10, 9), g(8, 9), g(10, 10), g(9, 8), g(0, 0), g(11, 9), g(0, 1), g(10, 8), g(0, 2), g(11, 10), g(0, 3), g(9, 10), g(0, 4)] },
    solution: [g(10, 11)], hint: "Nhóm trắng (10,9)-(10,10) chỉ còn đúng 1 khí — bít nốt." },
  { id: "go-3", game: "go", title: "Bắt quân góc bàn", difficulty: 1,
    setup: { moves: [g(9, 9), g(0, 0), g(0, 1), g(9, 8)] },
    solution: [g(1, 0)], hint: "Ở góc chỉ còn một khí (1,0)." },
  { id: "go-4", game: "go", title: "Bắt nhóm ba quân", difficulty: 2,
    setup: { moves: [g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(4, 7), g(5, 7), g(6, 5), g(0, 0), g(6, 6), g(0, 1), g(6, 7), g(0, 2), g(5, 4), g(0, 3)] },
    solution: [g(5, 8)], hint: "Nhóm trắng hàng 5 bị vây — chỉ còn khí (5,8)." },
  { id: "go-5", game: "go", title: "Bít khí cuối cùng", difficulty: 2,
    setup: { moves: [g(7, 8), g(8, 8), g(7, 9), g(8, 9), g(8, 10), g(9, 8), g(9, 7), g(0, 0), g(8, 7), g(0, 1)] },
    solution: [g(9, 9)], hint: "Nhóm trắng 3 quân chỉ còn khí (9,9)." },
  { id: "go-6", game: "go", title: "Ăn quân trên biên", difficulty: 1,
    setup: { moves: [g(9, 9), g(0, 5), g(0, 4), g(9, 8), g(0, 6), g(9, 7)] },
    solution: [g(1, 5)], hint: "Quân biên trên chỉ còn khí (1,5)." },
  { id: "go-7", game: "go", title: "Vây nhóm hai quân", difficulty: 2,
    setup: { moves: [g(9, 10), g(10, 10), g(9, 11), g(10, 11), g(11, 10), g(0, 0), g(11, 11), g(0, 1), g(10, 9), g(0, 2)] },
    solution: [g(10, 12)], hint: "Nhóm trắng chỉ còn khí bên phải." },
  { id: "go-8", game: "go", title: "Nối quân thoát vây", difficulty: 2,
    setup: { moves: [g(0, 0), g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(6, 5), g(0, 1), g(6, 6), g(0, 2), g(5, 7)] },
    solution: [g(5, 4)], hint: "Nhóm đen bị đe atari — chạy ra (5,4) để thêm khí." },
  { id: "go-9", game: "go", title: "Bắt ba quân góc", difficulty: 1,
    setup: { moves: [g(9, 9), g(0, 0), g(0, 2), g(0, 1), g(2, 0), g(1, 0)] },
    solution: [g(1, 1)], hint: "Nhóm trắng góc chỉ còn khí (1,1)." },
  { id: "go-10", game: "go", title: "Atari quân chạy biên", difficulty: 1,
    setup: { moves: [g(9, 9), g(3, 0), g(2, 0), g(9, 8), g(4, 0), g(9, 7)] },
    solution: [g(3, 1)], hint: "Quân trắng biên trái chỉ còn khí (3,1)." },
];
