import type { Puzzle } from "./types";

const N = 15;
const c = (r: number, col: number) => r * N + col;
const x = (r: number, col: number) => r * 9 + col;
const g = (r: number, col: number) => r * 19 + col;

export const PUZZLES: Puzzle[] = [
  /* ============ CARO — X đi trước, tìm nước mấu chốt ============ */
  { id: "caro-1", game: "caro", title: "Năm quân một đường", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(7, 8)], hint: "Hàng ngang của X sắp đủ 5.",
    explain: "Bốn quân X liền nhau, đầu còn trống — đặt quân thứ 5 là thắng ngay, O không kịp làm gì khác." },
  { id: "caro-2", game: "caro", title: "Đường chéo ẩn", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(4, 4), c(0, 0), c(5, 5), c(0, 1), c(6, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(8, 8)], hint: "Nhìn đường chéo xuôi từ góc trên.",
    explain: "Bốn quân nằm chéo từ (4,4) tới (7,7) — kéo dài bằng (8,8) là đủ 5 theo đường chéo." },
  { id: "caro-3", game: "caro", title: "Chặn trước khi muộn", difficulty: 2, theme: "Phòng thủ",
    setup: { moves: [c(8, 8), c(8, 4), c(0, 0), c(8, 5), c(0, 1), c(8, 6), c(0, 2), c(8, 7)] },
    solution: [c(8, 3)], hint: "O có 4 quân hàng 9 — chặn đầu còn trống mở.",
    explain: "O có 4 quân liền, đầu phải đã bị X bịt — chỉ còn đầu (8,3). Không chặn ngay, nước sau O thắng." },
  { id: "caro-4", game: "caro", title: "Bốn mở hai đầu", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(6, 4), c(0, 0), c(6, 5), c(0, 1), c(6, 6), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(6, 3)], hint: "X có 4 quân hàng 7 — nối đủ 5 là thắng.",
    explain: "Bốn quân hai đầu mở là thế thắng chắc: nối đầu nào cũng được, O chặn một đầu thì đánh đầu kia." },
  { id: "caro-5", game: "caro", title: "Chặn đúng một đầu", difficulty: 1, theme: "Phòng thủ",
    setup: { moves: [c(0, 0), c(8, 3), c(0, 1), c(8, 4), c(0, 2), c(8, 5), c(8, 7), c(8, 6)] },
    solution: [c(8, 2)], hint: "O có 4 quân, đầu phải đã bị X bịt — chỉ còn một đầu sống.",
    explain: "O đã để 4 quân với một đầu bị X chiếm — chỉ cần chặn đầu (8,2), hàng 5 của O chết hẳn." },
  { id: "caro-6", game: "caro", title: "Chéo lên phải", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(9, 3), c(0, 0), c(8, 4), c(0, 1), c(7, 5), c(0, 2), c(6, 6), c(0, 3)] },
    solution: [c(5, 7)], hint: "Đường chéo đi lên từ trái dưới.",
    explain: "Bốn quân X bậc thang đi lên từ trái dưới — ô (5,7) kéo dài đường chéo lên đủ 5." },
  { id: "caro-7", game: "caro", title: "Ba đôi ngang dọc", difficulty: 2, theme: "Nước đôi",
    setup: { moves: [c(7, 5), c(0, 0), c(7, 6), c(0, 1), c(5, 7), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(7, 7)], hint: "Một nước tạo hai hàng ba mở — O không chặn xuể.",
    explain: "(7,7) nối hàng ngang 5-6-7 thành mở 3, đồng thời nối dọc 5-6-7 thành mở 3 thứ hai. O chặn được một, mất hướng kia." },
  { id: "caro-8", game: "caro", title: "Phá ba đôi của đối thủ", difficulty: 2, theme: "Phòng thủ",
    setup: { moves: [c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(5, 7), c(0, 3), c(6, 7)] },
    solution: [c(7, 7)], hint: "O sắp đặt (7,7) tạo ba đôi — X chiếm trước giao điểm đó.",
    explain: "(7,7) là giao điểm O sẽ tạo nước đôi — chiếm trước một ô mà phá hai mối đe dọa cùng lúc." },
  { id: "caro-9", game: "caro", title: "Thắng cột dọc", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(3, 7), c(2, 7), c(4, 7), c(0, 0), c(5, 7), c(0, 1), c(6, 7), c(0, 2)] },
    solution: [c(7, 7)], hint: "Đầu trên đã bị O bịt — còn đầu dưới.",
    explain: "X có 4 quân dọc cột 8, đầu trên bị O chặn — nối đầu dưới (7,7) là đủ 5 với một đầu mở." },
  { id: "caro-10", game: "caro", title: "Ba đôi chéo ngang", difficulty: 2, theme: "Nước đôi",
    setup: { moves: [c(5, 5), c(0, 0), c(6, 6), c(0, 1), c(7, 5), c(0, 2), c(7, 6), c(0, 3)] },
    solution: [c(7, 7)], hint: "Giao điểm (7,7) nối được cả đường chéo lẫn hàng ngang.",
    explain: "(7,7) cùng lúc nối chéo 5-6-7 và ngang 5-6-7 — hai mở 3 cắt nhau tại một điểm, O chặn xuể đâu." },
  { id: "caro-11", game: "caro", title: "Nước đôi — hai mở ba", difficulty: 3, theme: "Nước đôi",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(6, 5), c(0, 2), c(8, 7), c(14, 14)] },
    solution: [c(7, 6), c(7, 3), c(5, 4), c(4, 3), c(9, 8)],
    hint: "Tìm ô mà X đánh vào sẽ có MỘT hàng ngang 3 và MỘT đường chéo 3 cùng mở hai đầu.",
    explain: "Nước (7,6) tạo mở 3 ngang và mở 3 chéo cùng lúc. O chặn ngang thì X bóp chéo thành mở 4 sống; O chặn đầu kia thì thắng đầu này. Người thua không phải do đi chậm — do đuổi theo hai mối đe dọa chỉ với một quân mỗi lượt." },

  /* ============ CỜ VUA ============ */
  { id: "chess-1", game: "chess", title: "Chiếu hết hàng cuối", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Vua đen không có ô thoát — đưa hậu xuống đáy.",
    explain: "Qe8# — ba tốt đen tự chặn đường vua, hàng cuối trống hoàn toàn. Đây là dạng chiếu hết cơ bản nhất." },
  { id: "chess-2", game: "chess", title: "Bẫy học trò", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1" },
    solution: [{ from: "h5", to: "f7" }], hint: "Hậu + tượng cùng nhắm f7 — tốt yếu nhất bàn cờ.",
    explain: "Qxf7# — bẫy Scholar 2 nước: hậu h5 và tượng c4 cùng chỉa vào f7, vua đen không có ai che." },
  { id: "chess-3", game: "chess", title: "Xe chiếu hết hàng cuối", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Đưa xe xuống hàng 8 — vua đen kẹt sau 3 tốt.",
    explain: "Rb8# — xe một mình cũng đủ kết liễu khi hàng cuối bị chính tốt địch chặn đường thoát." },
  { id: "chess-4", game: "chess", title: "Hai xe soi hàng", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "7k/R7/8/8/8/8/8/1R5K w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Xe a7 đã khóa hàng 7 — xe còn lại đặt hàng 8.",
    explain: "Rb8# — 'thang xe': một xe khóa hàng, xe kia kết liễu. Vua bị nhốt giữa hai hàng chiếu liên tục." },
  { id: "chess-5", game: "chess", title: "Xe ăn xe rồi hết", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Ăn xe e8 — chiếu hết luôn vì hàng 8 không ai thủ.",
    explain: "Rxe8# — xe đen gác hàng cuối nhưng không được xe thứ hai bảo vệ: ăn ngay và chiếu hết." },
  { id: "chess-6", game: "chess", title: "Nĩa mã vua và hậu", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "6k1/8/8/3q4/4N3/8/8/4K3 w - - 0 1" },
    solution: [{ from: "e4", to: "f6" }, { from: "g8", to: "f8" }, { from: "f6", to: "d5" }],
    hint: "Mã f6 chiếu vua g8, đồng thời treo hậu d5.",
    explain: "Nf6+ là nước nĩa: vua phải chạy, mã ăn hậu nước sau. Mã nhảy qua quân nên không thể bị chặn." },
  { id: "chess-7", game: "chess", title: "Skewer bắt hậu", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "4k3/4q3/8/8/8/8/8/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e7" }], hint: "Xe ăn hậu e7 chiếu — vua phải đổi xe cho hậu.",
    explain: "Rxe7+ xiên vua-hậu: vua đứng sau hậu trên cùng cột, chạy thì xe ăn hậu — đổi xe 5 điểm lấy hậu 9 điểm." },
  { id: "chess-8", game: "chess", title: "Hậu c8 kết liễu", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/7Q/6PP/6K1 w - - 0 1" },
    solution: [{ from: "h3", to: "c8" }], hint: "Hậu xuống hàng 8 — vua bị chính tốt mình chặn.",
    explain: "Qc8# — đường chéo h3-c8 mở sạch, vua đen không có ô thoát vì ba tốt d hàng cuối." },
  { id: "chess-9", game: "chess", title: "Ăn hậu giữa bàn", difficulty: 1, theme: "Chiến thuật",
    setup: { fen: "4k3/8/8/8/8/8/3q4/3R1K2 w - - 0 1" },
    solution: [{ from: "d1", to: "d2" }], hint: "Hậu đen d2 không ai giữ — xe đứng cạnh ăn ngay.",
    explain: "Rxd2 — hậu đen đang treo: đứng cạnh xe trắng mà không có quân nào bảo vệ. Nhìn quân 'treo' trước mỗi nước." },
  { id: "chess-10", game: "chess", title: "Hậu g7 sát", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5p1p/7P/8/8/8/1Q4P1/6K1 w - - 0 1" },
    solution: [{ from: "b2", to: "g7" }], hint: "Đường chéo b2–g7 mở sẵn; tốt h6 đỡ hậu trên g7.",
    explain: "Qxg7# — hậu ăn tốt g7, chiếu hàng cuối; tốt trắng h6 che ô thoát h7. Vua bị gông giữa hai cánh." },
  { id: "chess-11", game: "chess", title: "Tượng bắt xe tự do", difficulty: 1, theme: "Chiến thuật",
    setup: { fen: "4k3/8/8/8/3r4/8/8/4K1B1 w - - 0 1" },
    solution: [{ from: "g1", to: "d4" }], hint: "Xe d4 không ai giữ — đường chéo g1–d4 trống.",
    explain: "Bxd4 — xe đen đứng trên đường chéo tượng mà không có quân kề bên bảo vệ: ăn thẳng." },
  { id: "chess-12", game: "chess", title: "Hậu hi sinh — gông vua", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "5r1k/6pp/7N/8/2Q5/8/8/7K w - - 0 1" },
    solution: [{ from: "c4", to: "g8" }, { from: "f8", to: "g8" }, { from: "h6", to: "f7" }],
    hint: "Nước 1: hậu nhảy vào g8 — ngay cạnh vua. Mã h6 đang bảo vệ ô đó. Đen buộc phải dùng xe ăn hậu.",
    explain: "Chiếu bí Philidor: Qg8+ hi sinh hậu; xe đen buộc phải ăn (Rxg8), và Nf7# kết liễu — vua bị chính xe và hai tốt của mình gông kín, mã không thể bị bắt vì nhảy qua." },
  { id: "chess-13", game: "chess", title: "Phong cấp kết liễu", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/4Pppp/8/8/8/8/5PPP/6K1 w - - 0 1" },
    solution: [{ from: "e7", to: "e8", promotion: "q" }], hint: "Tốt e7 chỉ còn một bước — phong hậu ngay ở ô e8.",
    explain: "e8=Q# — phong cấp và chiếu hết trong cùng một nước: hàng cuối trống, ba tốt đen chặn kín đường vua. Phong xe (e8=R) cũng hết — cứ phong hậu theo thói quen." },

  /* ============ CỜ TƯỚNG — đỏ đi trước ============ */
  { id: "xq-1", game: "xiangqi", title: "Pháo ăn mã đầu ván", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [] },
    solution: [{ from: x(7, 1), to: x(0, 1) }], hint: "Pháo đỏ (7,1) nhảy qua ngòi pháo đen (2,1) để ăn mã.",
    explain: "Pháo chỉ ăn được qua đúng một ngòi — pháo đen (2,1) chính là ngòi sẵn cho phép pháo đỏ ăn mã (0,1)." },
  { id: "xq-2", game: "xiangqi", title: "Pháo trung lộ ăn tốt", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [{ from: x(7, 1), to: x(7, 4) }, { from: x(0, 1), to: x(2, 2) }] },
    solution: [{ from: x(7, 4), to: x(3, 4) }], hint: "Tốt đỏ (6,4) là ngòi — pháo ăn tốt đen giữa sông.",
    explain: "Pháo vào trung lộ phối hợp với tốt đỏ (6,4) làm ngòi: ăn tốt đen (4,4) và uy hiếp trực tiếp cung tướng." },
  { id: "xq-3", game: "xiangqi", title: "Xe đâm thẳng bắt tướng", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/9/9/4R4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 4), to: x(0, 4) }], hint: "Cột giữa trống hoàn toàn — xe lên tận bắt tướng.",
    explain: "Xe mạnh nhất khi đường mở: cột giữa trống, xe lao thẳng tới tướng đen không ai chặn." },
  { id: "xq-4", game: "xiangqi", title: "Mã nhảy chiếu hết", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/9/9/2H6/4R4/9/9/9/4G4 r" },
    solution: [{ from: x(4, 2), to: x(2, 3) }], hint: "Mã (2,3) chiếu — tướng kẹt giữa hai sĩ, ô (1,4) đã bị xe (5,4) khóa.",
    explain: "Mã nhảy (2,3) chiếu tướng. Tướng không chạy được vì xe đỏ (5,4) kiểm soát ô (1,4) — mã chiếu luôn đi kèm một quân khóa đường thoát." },
  { id: "xq-5", game: "xiangqi", title: "Pháo bắn xe qua ngòi", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "r2aga3/9/p8/9/9/C8/9/9/9/3G5 r" },
    solution: [{ from: x(5, 0), to: x(0, 0) }], hint: "Chỉ đúng một quân cản giữa — ngòi pháo hoàn hảo.",
    explain: "Pháo ăn xe (0,0) nhờ ngòi tốt đen (2,0): giữa pháo và xe có đúng một quân là đủ." },
  { id: "xq-6", game: "xiangqi", title: "Mã tẩu ăn pháo", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "3aga3/9/9/9/2c6/9/1H7/9/9/3G5 r" },
    solution: [{ from: x(6, 1), to: x(4, 2) }], hint: "Chân mã (5,1) trống — nhảy lên ăn pháo.",
    explain: "Mã bị chặn chân thì vô dụng, chân trống thì nguy hiểm: mã (6,1) nhảy ăn pháo (4,2) vì ô (5,1) trống." },
  { id: "xq-7", game: "xiangqi", title: "Tốt qua sông ăn mã", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "3aga3/9/9/9/3Ph4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 3), to: x(4, 4) }], hint: "Tốt đã qua sông được đi ngang — ăn mã ngay.",
    explain: "Qua sông tốt 'lột xác': được đi ngang. Tốt (4,3) ngang sang ăn mã (4,4) — giá trị tốt tăng gấp bội sau sông." },
  { id: "xq-8", game: "xiangqi", title: "Xe ăn sĩ phá cung", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "3aga3/3R5/9/9/9/9/9/9/9/3G5 r" },
    solution: [{ from: x(1, 3), to: x(0, 3) }], hint: "Ăn sĩ (0,3) — mở mặt tướng và chiếu luôn.",
    explain: "Rxa3+ vừa ăn sĩ vừa chiếu: sĩ là tường thành cung — tướng ăn lại được xe, nhưng mất sĩ là lộ mặt tướng, mầm họa về sau." },
  { id: "xq-9", game: "xiangqi", title: "Tốt độc phá sát", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/4P4/9/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(1, 4), to: x(0, 4) }], hint: "Tốt lao xuống bắt tướng — sĩ không cứu được.",
    explain: "Tốt sát cung là pháo đài sống: lao xuống (0,4) ép tướng đổi chỗ, còn tốt thì đeo bám không rời. Một tốt trong cung đáng bằng xe ngoài biên." },
  { id: "xq-10", game: "xiangqi", title: "Mã góc pháo bộ", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/5H3/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 5), to: x(0, 4) }], hint: "Mã (2,5) nhảy góc (0,4) — chân mã (1,5) trống.",
    explain: "Mã nhảy góc cung là đòn kết liễu kinh điển: từ (2,5) tới (0,4), tướng bị nhốt giữa các sĩ không có ô thoát." },
  { id: "xq-11", game: "xiangqi", title: "Pháo yểm trung lộ", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/3ppp3/9/9/9/3C5/9/9/9/4G4 r" },
    solution: [{ from: x(5, 3), to: x(5, 4) }], hint: "Đen đã tự khóa kín năm ô thoát của tướng. Pháo chỉ cần vào cột giữa — nhớ ngòi.",
    explain: "Năm ô chạy của tướng bị chính sĩ và tốt đen chôn kín. Pháo vào (5,4) là chiếu và đen không gỡ được: chặn cột thì pháo ăn qua ngòi tốt (1,4), chạy thì hết đường. Bài học: cung đối thủ tự đóng khóa chính là đòn pháo trung." },
  { id: "xq-12", game: "xiangqi", title: "Song xe nhốt cung", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "4ga3/8R/R3e4/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 0), to: x(0, 0) }], hint: "Một xe khóa hàng 1, xe còn lại chiếu hàng 0 — tướng bị nhốt giữa hai 'tường'.",
    explain: "Xe (1,8) khóa hết hàng 1, xe (0,0) chiếu xuyên hàng 0. Hai xe tàn cuộc là cặp sát thủ: luôn kết liễu bằng cách bó vua vào biên rồi chiếu hàng." },
  { id: "xq-13", game: "xiangqi", title: "Mã đe đôi", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "3aga3/r1c6/4p4/9/9/H8/9/9/9/4G4 r" },
    solution: [{ from: x(5, 0), to: x(3, 1) }, { from: x(1, 0), to: x(2, 0) }, { from: x(3, 1), to: x(1, 2) }],
    hint: "Mã nhảy lên (3,1): nhìn xem nó đang chĩa vào những quân đen nào cùng lúc?",
    explain: "Mã (3,1) đe đôi xe (1,0) và pháo (1,2). Đen phải cứu xe (quân mạnh hơn), mã ung dung ăn pháo nước sau — đòn đe đôi của mã luôn thắng vì mã nhảy qua, không chặn được." },
  { id: "xq-14", game: "xiangqi", title: "Mã đè sĩ", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3aga3/R8/4c4/9/2H6/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 2), to: x(2, 3) }], hint: "Xe (1,0) đã khóa hàng 1. Mã chỉ cần một điểm nhảy trống chân mà chiếu được tướng.",
    explain: "Xe (1,0) soi cả hàng 1, mã (2,3) chiếu tướng qua ô chân (1,3) trống. Pháo đen (2,4) không thể ăn mã vì kề nhau không ngòi — 'mã đè sĩ' là dạng chiếu hết kinh điển: xe khóa đường, mã kết liễu." },
  { id: "xq-15", game: "xiangqi", title: "Xe buộc pháo, xuyên hàng bắt mã", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "4g4/9/9/h3c4/9/7R1/9/9/9/4G4 r" },
    solution: [{ from: x(5, 7), to: x(3, 7) }, { from: x(3, 4), to: x(2, 4) }, { from: x(3, 7), to: x(3, 0) }],
    hint: "Xe xuống (3,7) đe pháo. Pháo chạy thì hàng 3 trống — xe muốn ăn ai?",
    explain: "Xe (3,7) đe pháo buộc đen phải bê pháo khỏi hàng 3 — và hàng 3 vừa trống chính là xa lộ xe lao tới bắt mã (3,0). Đe một quân để mở đường ăn quân khác: cách 'đi mòn' xe kinh điển." },

  /* ============ CỜ VÂY — đen đi trước, bắt quân ============ */
  { id: "go-1", game: "go", title: "Bắt quân đầu tiên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(10, 9), g(0, 0), g(11, 10), g(0, 1)] },
    solution: [g(10, 11)], hint: "Trắng (10,10) chỉ còn 1 khí.",
    explain: "Quân trắng chỉ còn đúng một khí (10,11) — lấp khí cuối là bắt, quân bị nhấc khỏi bàn." },
  { id: "go-2", game: "go", title: "Bắt nhóm hai quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(10, 9), g(8, 9), g(10, 10), g(9, 8), g(0, 0), g(11, 9), g(0, 1), g(10, 8), g(0, 2), g(11, 10), g(0, 3), g(9, 10), g(0, 4)] },
    solution: [g(10, 11)], hint: "Nhóm trắng (10,9)-(10,10) chỉ còn đúng 1 khí — bít nốt.",
    explain: "Nhóm liền nhau chia sẻ khí — bít khí cuối của CẢ NHÓM thì cả nhóm bị bắt cùng lúc." },
  { id: "go-3", game: "go", title: "Bắt quân góc bàn", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 0), g(0, 1), g(9, 8)] },
    solution: [g(1, 0)], hint: "Ở góc chỉ còn một khí (1,0).",
    explain: "Góc bàn chỉ có 2 khí (đất là tường) — quân góc yếu nhất, bắt dễ nhất." },
  { id: "go-4", game: "go", title: "Bắt nhóm ba quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(4, 7), g(5, 7), g(6, 5), g(0, 0), g(6, 6), g(0, 1), g(6, 7), g(0, 2), g(5, 4), g(0, 3)] },
    solution: [g(5, 8)], hint: "Nhóm trắng hàng 5 bị vây — chỉ còn khí (5,8).",
    explain: "Nhóm ba quân chia sẻ đúng một khí cuối — bít (5,8) là nhấc cả nhóm. Đếm khí nhóm, đừng đếm từng quân." },
  { id: "go-5", game: "go", title: "Bít khí cuối cùng", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(7, 8), g(8, 8), g(7, 9), g(8, 9), g(8, 10), g(9, 8), g(9, 7), g(0, 0), g(8, 7), g(0, 1), g(10, 8), g(0, 2)] },
    solution: [g(9, 9)], hint: "Nhóm trắng 3 quân chỉ còn khí (9,9).",
    explain: "Trước khi đánh, luôn đếm khí của nhóm bị vây: (9,9) là khí duy nhất còn lại của nhóm trắng." },
  { id: "go-6", game: "go", title: "Ăn quân trên biên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 5), g(0, 4), g(9, 8), g(0, 6), g(9, 7)] },
    solution: [g(1, 5)], hint: "Quân biên trên chỉ còn khí (1,5).",
    explain: "Quân biên ít khí hơn giữa bàn — ở biên chỉ cần 3 quân là nhốt, ở giữa cần 4." },
  { id: "go-7", game: "go", title: "Vây nhóm hai quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(9, 11), g(10, 11), g(11, 10), g(0, 0), g(11, 11), g(0, 1), g(10, 9), g(0, 2)] },
    solution: [g(10, 12)], hint: "Nhóm trắng chỉ còn khí bên phải.",
    explain: "Nhóm trắng (10,10)-(10,11) đã bị bao 3 phía — khí cuối (10,12) là chỗ dựa duy nhất của nó." },
  { id: "go-8", game: "go", title: "Nối quân thoát vây", difficulty: 2, theme: "Sống chết",
    setup: { moves: [g(0, 0), g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(6, 5), g(0, 1), g(6, 6), g(0, 2), g(5, 7)] },
    solution: [g(5, 4)], hint: "Nhóm đen bị đe atari — chạy ra (5,4) để thêm khí.",
    explain: "Atari (còn 1 khí) phải chạy ngay: (5,4) nối thêm quân và mở khí mới. Để atari không chạy là mất quân chỉ vì quên đếm." },
  { id: "go-9", game: "go", title: "Bắt ba quân góc", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 0), g(0, 2), g(0, 1), g(2, 0), g(1, 0)] },
    solution: [g(1, 1)], hint: "Nhóm trắng góc chỉ còn khí (1,1).",
    explain: "Nhóm 3 quân ở góc có tối đa 6 khí nhưng bị bao kín chỉ còn (1,1) — góc là nơi dễ bắt nhất bàn cờ." },
  { id: "go-10", game: "go", title: "Atari quân chạy biên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(3, 0), g(2, 0), g(9, 8), g(4, 0), g(9, 7)] },
    solution: [g(3, 1)], hint: "Quân trắng biên trái chỉ còn khí (3,1).",
    explain: "Quân chạy dọc biên rất đuối khí: mỗi bước chỉ mở được 2-3 khí. Đánh vào (3,1) là atari — quân trắng phải chạy dài hoặc chết." },

  /* ===== CARO mới ===== */
  { id: "caro-12", game: "caro", title: "Chéo xuôi kết liễu", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(2, 2), c(0, 0), c(3, 3), c(0, 1), c(4, 4), c(0, 2), c(5, 5), c(0, 3)] },
    solution: [c(6, 6)], hint: "Đường chéo từ góc trên trái đã có 4 quân.",
    explain: "Bốn quân X nằm dọc đường chéo chính — thêm (6,6) là đủ 5, O chặn không kịp." },
  { id: "caro-13", game: "caro", title: "Chặn cột dọc", difficulty: 1, theme: "Phòng thủ",
    setup: { moves: [c(4, 7), c(5, 7), c(0, 0), c(6, 7), c(0, 1), c(7, 7), c(0, 2), c(8, 7)] },
    solution: [c(9, 7)], hint: "O có 4 quân cột 8, đầu trên đã bị X bịt — còn đầu dưới.",
    explain: "Đầu trên của hàng O đã bị X chặn — chỉ cần bịt nốt đầu dưới (9,7), hàng 5 của O không bao giờ hoàn thành." },
  { id: "caro-14", game: "caro", title: "Bịt đầu duy nhất", difficulty: 1, theme: "Phòng thủ",
    setup: { moves: [c(7, 7), c(7, 3), c(0, 0), c(7, 4), c(0, 1), c(7, 5), c(0, 2), c(7, 6)] },
    solution: [c(7, 2)], hint: "O có 4 quân hàng 8 — một đầu đã bị X chiếm.",
    explain: "O liền 4 với đầu phải đã bị X bịt — chặn nốt đầu trái (7,2) là hàng của O chết hẳn." },
  { id: "caro-15", game: "caro", title: "Năm quân cột dọc", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(4, 2), c(0, 0), c(5, 2), c(0, 1), c(6, 2), c(0, 2), c(7, 2), c(0, 3)] },
    solution: [c(3, 2)], hint: "Cột 3 đã có 4 quân X — nối đầu trên.",
    explain: "Bốn quân dọc cột, hai đầu đều trống — nối (3,2) là thắng ngay theo cột dọc." },
  { id: "caro-16", game: "caro", title: "Hai mở ba cắt nhau", difficulty: 2, theme: "Nước đôi",
    setup: { moves: [c(7, 5), c(0, 0), c(7, 6), c(0, 1), c(5, 5), c(0, 2), c(6, 6), c(0, 3)] },
    solution: [c(7, 7)], hint: "Một ô tạo đồng thời mở 3 ngang và mở 3 chéo.",
    explain: "(7,7) vừa hoàn thành hàng ngang (7,5)-(7,7) vừa nối đường chéo (5,5)-(7,7) — hai mở 3 cùng lúc, O chỉ chặn được một." },
  { id: "caro-17", game: "caro", title: "Chặn mở ba", difficulty: 2, theme: "Phòng thủ",
    setup: { moves: [c(0, 0), c(6, 4), c(0, 1), c(6, 5), c(0, 2), c(6, 6), c(1, 1), c(9, 9)] },
    solution: [c(6, 3)], hint: "O có mở 3 hàng 7 — chặn một đầu trước khi nó thành mở 4.",
    explain: "Mở 3 chưa thua ngay nhưng để yên là mất: chặn một đầu, đầu kia dù O nối cũng chỉ thành 4 bị khóa một đầu." },
  { id: "caro-18", game: "caro", title: "Chéo ngược quyết định", difficulty: 2, theme: "Tấn công",
    setup: { moves: [c(8, 2), c(0, 0), c(7, 3), c(0, 1), c(6, 4), c(0, 2), c(5, 5), c(0, 3)] },
    solution: [c(4, 6)], hint: "Đường chéo ngược từ dưới lên đã đủ 4 quân.",
    explain: "Bốn quân X bậc thang theo chéo ngược (8,2) tới (5,5) — nối (4,6) là đủ 5." },
  { id: "caro-19", game: "caro", title: "Mở bốn không thể chặn", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(10, 10), c(0, 3)] },
    solution: [c(7, 3), c(7, 2), c(7, 7)],
    hint: "Nối dài hàng 8 thành mở 4 — O chỉ chặn được một đầu.",
    explain: "X nối thành 4 quân hai đầu mở. O buộc phải chặn (7,2), X đặt đầu kia (7,7) là đủ 5. Mở 4 hai đầu là thế không thể cứu." },
  { id: "caro-20", game: "caro", title: "Lấp khe thành bốn", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 7), c(0, 2), c(11, 11), c(0, 3)] },
    solution: [c(7, 6), c(7, 3), c(7, 8)],
    hint: "Ô trống giữa hàng — lấp vào để có 4 quân liền.",
    explain: "Điền (7,6) vào khe hở tạo hàng 4 hai đầu mở. O chặn (7,3) thì X thắng ở (7,8) — hàng có khe cũng nguy hiểm như hàng liền." },
  { id: "caro-21", game: "caro", title: "Bốn dọc hai đầu", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(4, 9), c(0, 0), c(5, 9), c(0, 1), c(6, 9), c(0, 2), c(12, 3), c(0, 3)] },
    solution: [c(7, 9), c(3, 9), c(8, 9)],
    hint: "Kéo dài cột 10 thành 4 quân — hai đầu đều sống.",
    explain: "X nối cột thành 4 quân hai đầu mở. O chặn đầu trên (3,9), X nối đầu dưới (8,9) đủ 5." },
  { id: "caro-22", game: "caro", title: "Chéo chính mở bốn", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(3, 3), c(0, 0), c(4, 4), c(0, 1), c(5, 5), c(0, 2), c(9, 1), c(1, 9)] },
    solution: [c(6, 6), c(2, 2), c(7, 7)],
    hint: "Đường chéo xuôi thiếu một mắt xích là thành mở 4.",
    explain: "Nối (6,6) thành 4 quân chéo hai đầu mở — O chặn (2,2) thì X thắng ở (7,7)." },
  { id: "caro-23", game: "caro", title: "Đòn liên hoàn hai hàng", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(8, 4), c(1, 0), c(8, 5), c(1, 1), c(8, 6), c(1, 2)] },
    solution: [c(7, 3), c(7, 2), c(8, 3), c(8, 2), c(7, 7)],
    hint: "X có hai mở 3 chồng nhau — cứ biến lần lượt thành mở 4.",
    explain: "Hai hàng mở 3 song song. X tạo mở 4 hàng 8, O chặn; X tạo mở 4 hàng 9, O chặn tiếp; nhưng mở 4 đầu tiên vẫn còn đầu sống — X quay lại thắng ở (7,7)." },
  { id: "caro-24", game: "caro", title: "Chéo ngược ép biên", difficulty: 3, theme: "Tấn công",
    setup: { moves: [c(9, 3), c(0, 0), c(8, 4), c(0, 1), c(7, 5), c(0, 2), c(4, 10), c(0, 3)] },
    solution: [c(6, 6), c(5, 7), c(10, 2)],
    hint: "Nối đường chéo ngược thành mở 4 — đầu dưới chạy tới biên vẫn thắng.",
    explain: "(6,6) tạo 4 quân chéo ngược. O chặn (5,7), X nối đầu kia (10,2) đủ 5 tận cùng đường chéo." },
  { id: "caro-25", game: "caro", title: "Chặn chéo kịp lúc", difficulty: 1, theme: "Phòng thủ",
    setup: { moves: [c(11, 3), c(10, 4), c(0, 0), c(9, 5), c(0, 1), c(8, 6), c(0, 2), c(7, 7)] },
    solution: [c(6, 8)], hint: "O có 4 quân chéo ngược — đầu dưới đã bị X bịt.",
    explain: "Hàng chéo của O có một đầu bị X chặn sẵn ở (11,3) — chỉ cần bịt đầu trên (6,8) là xong." },

  /* ===== CỜ VUA mới ===== */
  { id: "chess-14", game: "chess", title: "Vua ăn mã tự do", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "4k3/8/8/8/8/8/4n3/4K3 w - - 0 1" },
    solution: [{ from: "e1", to: "e2" }], hint: "Mã đen e2 không ai giữ — vua ăn ngay.",
    explain: "Kxe2 — mã đen đi quá xa không ai bảo vệ. Vua cũng là quân chiến đấu, đừng ngại dùng vua bắt quân treo." },
  { id: "chess-15", game: "chess", title: "Hậu quét cột a", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "r3k3/8/8/8/8/8/8/Q3K3 w - - 0 1" },
    solution: [{ from: "a1", to: "a8" }], hint: "Xe đen a8 không ai giữ — cột a trống hoàn toàn.",
    explain: "Qxa8+ — xe đen đứng lẻ loi trên cột mở. Trước khi đi nước đẹp, hãy tìm xem đối thủ có quân nào đang 'treo'." },
  { id: "chess-16", game: "chess", title: "Tấn công lộ hậu", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "4q1k1/8/8/8/4B3/8/8/4R1K1 w - - 0 1" },
    solution: [{ from: "e4", to: "d5" }, { from: "g8", to: "f8" }, { from: "e1", to: "e8" }],
    hint: "Tượng e4 đang chặn đường xe e1 tới hậu e8 — nhích tượng ra chỗ nào vừa chiếu vua?",
    explain: "Bd5+ là nước đôi: tượng chiếu vua g8, đồng thời mở đường xe e1 bắt hậu e8. Vua phải chạy, hậu không ai cứu — đòn 'tấn công lộ' kinh điển." },
  { id: "chess-17", game: "chess", title: "Hai xe ép hàng cuối", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "5rk1/5ppp/8/4R3/8/8/5PPP/4R1K1 w - - 0 1" },
    solution: [{ from: "e5", to: "e8" }, { from: "f8", to: "e8" }, { from: "e1", to: "e8" }],
    hint: "Xe f8 đang bị ghim — nó chạy đi đâu là thua ngay.",
    explain: "Re8! ghim xe f8: xe đen buộc phải đổi, Rxe8# kết liễu — hàng cuối kín bởi ba tốt luôn là điểm yếu chí mạng." },
  { id: "chess-18", game: "chess", title: "Đổi xe khai hàng", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "2r3k1/5ppp/8/3R4/8/8/5PPP/3R2K1 w - - 0 1" },
    solution: [{ from: "d5", to: "d8" }, { from: "c8", to: "d8" }, { from: "d1", to: "d8" }],
    hint: "Chiếu trước — xe đen buộc phải đổi, rồi xe thứ hai làm gì?",
    explain: "Rd8+ buộc Rxd8, rồi Rxd8# — hai xe chồng cột đổi quân để chiếu hết hàng cuối, dạng tàn cuộc cơ bản nhất của đôi xe." },
  { id: "chess-19", game: "chess", title: "Hậu ăn tốt sát vua", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "7k/6pp/6P1/7Q/8/8/8/6K1 w - - 0 1" },
    solution: [{ from: "h5", to: "h7" }], hint: "Hậu ăn tốt h7 — tốt trắng g6 đang yểm trợ ô đó.",
    explain: "Qxh7# — kiểu chiếu hết Damiano: hậu áp sát vua nhờ tốt g6 bảo vệ, vua bị chính tốt g7 chặn đường thoát." },
  { id: "chess-20", game: "chess", title: "Chiếu hết kiểu Ả Rập", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "7k/6p1/5N2/8/8/8/6K1/4R3 w - - 0 1" },
    solution: [{ from: "e1", to: "h1" }], hint: "Mã f6 đã khóa ô g8 — đưa xe sang cột h.",
    explain: "Rh1# — mã f6 kiểm soát g8 và h7, vua bị nhốt vào góc bởi chính tốt g7. Xe + mã là cặp chiếu hết kinh điển nhất." },
  { id: "chess-21", game: "chess", title: "Vua bị hai xe chặn vai", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3rkr2/8/8/8/8/8/4Q3/4K3 w - - 0 1" },
    solution: [{ from: "e2", to: "e6" }], hint: "Vua đen kẹt giữa hai xe của chính mình — hậu chiếu cột e.",
    explain: "Qe6# — chiếu hết 'epaulette': hai xe đen đứng hai bên vua như đôi épaulette chặn đường chạy, hậu chiếu giữa là hết." },
  { id: "chess-22", game: "chess", title: "Hậu mã sát góc", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "7k/6pp/8/6N1/8/7Q/8/6K1 w - - 0 1" },
    solution: [{ from: "h3", to: "h7" }], hint: "Mã g5 đang giữ ô h7 — hậu ăn tốt góc.",
    explain: "Qxh7# — hậu ăn tốt được mã g5 yểm trợ, vua hết đường vì tốt g7 chặn. Hậu + mã là cặp ám sát mạnh nhất gần cung." },
  { id: "chess-23", game: "chess", title: "Mở cửa sổ cho vua", difficulty: 2, theme: "Phòng thủ",
    setup: { fen: "4r1k1/5ppp/8/8/8/8/5PPP/6K1 w - - 0 1" },
    solution: [{ from: "h2", to: "h3" }], hint: "Đen đe Re1# — hàng cuối của bạn đang kín mít.",
    explain: "h3! tạo 'luồng gió': nếu đen Re1+, vua chạy h2 thoát. Khi chưa có đòn tấn công, trước tiên hãy vá điểm yếu hàng cuối." },
  { id: "chess-24", game: "chess", title: "Nĩa mã vua và xe", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "r3k3/8/8/1N6/8/8/8/4K3 w - - 0 1" },
    solution: [{ from: "b5", to: "c7" }, { from: "e8", to: "d8" }, { from: "c7", to: "a8" }],
    hint: "Ô c7 vừa chiếu vua e8, vừa chĩa vào xe a8.",
    explain: "Nc7+ nĩa đôi vua-xe: vua phải chạy, Nxa8 ăn xe nước sau. Ô c7 là 'miệng sói' kinh điển của mã trắng." },
  { id: "chess-25", game: "chess", title: "Gối hậu vào góc có tốt đỡ", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5p1p/6pP/8/8/8/1Q6/6K1 w - - 0 1" },
    solution: [{ from: "b2", to: "g7" }], hint: "Đường chéo b2–g7 trống; tốt h6 đang đỡ ô g7.",
    explain: "Qg7# — hậu ngồi ngay cạnh vua nhưng có tốt h6 bảo vệ: vua không ăn được, mọi ô chạy đều bị hậu khóa." },

  /* ===== CỜ TƯỚNG mới ===== */
  { id: "xq-16", game: "xiangqi", title: "Mã tẩu bắt tướng", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "3aga3/2H6/9/9/9/9/9/9/9/3G5 r" },
    solution: [{ from: x(1, 2), to: x(0, 4) }], hint: "Chân mã (1,3) trống — mã nhảy thẳng vào đầu tướng.",
    explain: "Mã (1,2) nhảy góc ăn tướng ngay — tướng kẹt giữa hai sĩ không ai đỡ được đòn mã tẩu." },
  { id: "xq-17", game: "xiangqi", title: "Xe quét mã biên", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "h2aga3/9/9/9/9/9/9/R8/9/5G3 r" },
    solution: [{ from: x(7, 0), to: x(0, 0) }], hint: "Cột 0 trống hoàn toàn — mã đen đứng lẻ loi.",
    explain: "Xe lao thẳng cột biên ăn mã — quân địch đứng không ai bảo vệ là 'quân treo', ăn ngay không tiếc." },
  { id: "xq-18", game: "xiangqi", title: "Xe chém tốt lật mặt", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "R2ag4/3Pp2H1/9/9/9/9/9/9/9/3GR4 r" },
    solution: [{ from: x(9, 4), to: x(1, 4) }], hint: "Tốt đen (1,4) đang chắn cột 4 — xe ăn nó sẽ chiếu gì?",
    explain: "Rxe4 chiếu: tướng không ăn được vì tốt đỏ (1,3) yểm, không chạy được vì mã (1,7) khóa (0,5) — sĩ đen bị xe đỏ (0,0) ghim nên không cứu được. Chiếu hết." },
  { id: "xq-19", game: "xiangqi", title: "Mã góc, xe khóa cung", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3aga3/7R1/9/1H7/9/9/9/9/9/3G5 r" },
    solution: [{ from: x(3, 1), to: x(1, 2) }], hint: "Mã nhảy (1,2) chiếu — xe đỏ hàng 1 đang khóa ô nào của tướng?",
    explain: "H (1,2) chiếu tướng, xe đỏ (1,8) khóa ô (1,4) — hai sĩ chiếm hết hai bên, tướng không còn đường. Chiếu hết." },
  { id: "xq-20", game: "xiangqi", title: "Tốt xông cung — sĩ bị khóa", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "R2aga2R/3P5/4P4/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 4), to: x(1, 4) }], hint: "Tốt lao xuống (1,4) chiếu — hai sĩ đen tại sao không bắt được nó?",
    explain: "P (1,4) chiếu: hai sĩ đen đều bị ghim bởi hai xe đỏ hàng 0 (sĩ đi là tướng lộ mặt), tốt (1,4) được tốt (1,3) yểm. Chiếu hết." },
  { id: "xq-21", game: "xiangqi", title: "Pháo trung — ngòi tốt chết", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3aga3/4p4/9/9/9/C8/9/9/9/4G4 r" },
    solution: [{ from: x(5, 0), to: x(5, 4) }], hint: "Pháo vào cột giữa — tốt đen (1,4) chính là ngòi, và nó không dời đi đâu được.",
    explain: "C (5,4) chiếu qua ngòi tốt (1,4): tốt đen đi tới vẫn nằm trên cột nên ngòi không mất, hai sĩ bị chính tốt chặn không chen vào được. Chiếu hết." },
  { id: "xq-22", game: "xiangqi", title: "Xe phá tượng — quét cung", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "R2ag4/7H1/2H1e4/9/9/9/9/9/9/3GR4 r" },
    solution: [{ from: x(9, 4), to: x(2, 4) }],
    hint: "Xe ăn tượng mở cột — sĩ đen muốn lên chặn nhưng bị ghim.",
    explain: "Rxe4 chiếu: sĩ (0,3) bị xe đỏ hàng 0 ghim không dám đi, tướng hết ô vì (0,5) bị mã (1,7) khóa. Chiếu hết." },
  { id: "xq-23", game: "xiangqi", title: "Xe phá tượng cánh phải", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "4g1a1R/1H7/4e1H2/9/9/9/9/9/9/3GR4 r" },
    solution: [{ from: x(9, 4), to: x(2, 4) }],
    hint: "Cánh đối diện của bài trước — sĩ (0,5) cũng bị ghim như thế nào?",
    explain: "Rxe4 chiếu: sĩ (0,5) bị xe đỏ hàng 0 ghim, (0,3) bị mã (1,1) khóa — tướng không lối thoát. Chiếu hết." },
  { id: "xq-24", game: "xiangqi", title: "Song mã khóa cung", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/9/5H3/4H4/9/9/9/9/3G5 r" },
    solution: [{ from: x(4, 4), to: x(2, 3) }], hint: "Mã trên nhảy chiếu — mã dưới đang khóa ô chạy của tướng.",
    explain: "H (2,3) chiếu tướng, mã (3,5) khóa ô (1,4) — hai sĩ chiếm hai bên, đòn mã không thể chặn. Chiếu hết." },
  { id: "xq-25", game: "xiangqi", title: "Xe dọa mã, quét pháo", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "3aga3/9/9/9/9/R1h3c2/9/9/9/5G3 r" },
    solution: [{ from: x(5, 0), to: x(5, 1) }, { from: x(5, 2), to: x(3, 1) }, { from: x(5, 1), to: x(5, 6) }],
    hint: "Xe áp sát đe mã — mã chạy đi thì pháo trần trụi.",
    explain: "Xe (5,1) đe mã buộc mã chạy; hàng 5 vừa trống, xe quét ngang ăn pháo (5,6) — đe một quân để bắt quân khác." },

  /* ===== CỜ VÂY mới ===== */
  { id: "go-11", game: "go", title: "Bít khí quân đơn", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(4, 5), g(5, 5), g(5, 4), g(0, 0), g(5, 6), g(0, 1)] },
    solution: [g(6, 5)], hint: "Quân trắng (5,5) chỉ còn một khí phía dưới.",
    explain: "Quân trắng bị vây ba phía — đặt vào khí cuối (6,5) là nhấc nó khỏi bàn." },
  { id: "go-12", game: "go", title: "Bắt đôi quân", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(7, 8), g(8, 8), g(7, 9), g(8, 9), g(8, 7), g(0, 0), g(9, 8), g(0, 1), g(9, 9), g(0, 2)] },
    solution: [g(8, 10)], hint: "Nhóm trắng hai quân chỉ còn khí bên phải.",
    explain: "Nhóm hai quân chia sẻ khí — bít (8,10) là bắt cả đôi cùng lúc." },
  { id: "go-13", game: "go", title: "Chạy atari ra ngoài", difficulty: 1, theme: "Sống chết",
    setup: { moves: [g(6, 6), g(5, 6), g(0, 0), g(6, 5), g(0, 1), g(6, 7)] },
    solution: [g(7, 6)], hint: "Quân đen (6,6) đang bị atari — chạy xuống mở khí.",
    explain: "Atari phải chạy ngay: nối (7,6) đưa nhóm ra chỗ rộng với 3 khí mới." },
  { id: "go-14", game: "go", title: "Vây đôi quân biên", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(0, 4), g(0, 5), g(1, 5), g(0, 6), g(1, 6), g(9, 9)] },
    solution: [g(0, 7)], hint: "Nhóm trắng trên biên chỉ còn khí (0,7).",
    explain: "Ở biên quân chỉ có 3 phía chạy — hai quân bị vây ba mặt là chỉ còn một khí duy nhất." },
  { id: "go-15", game: "go", title: "Bắt nhóm chữ L", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(9, 11), g(10, 11), g(10, 9), g(11, 10), g(11, 9), g(0, 0), g(11, 11), g(0, 1), g(10, 12), g(0, 2)] },
    solution: [g(12, 10)], hint: "Nhóm trắng ba quân chỉ còn khí phía dưới.",
    explain: "Đếm khí của cả nhóm, không đếm từng quân: ba quân chung nhau đúng một khí (12,10)." },
  { id: "go-16", game: "go", title: "Bắt đôi quân góc", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 0), g(0, 1), g(1, 0), g(2, 0), g(5, 5)] },
    solution: [g(1, 1)], hint: "Nhóm trắng góc chỉ còn khí chéo vào trong.",
    explain: "Góc bàn là nơi quân ít khí nhất — hai quân góc chỉ cần hai điểm bao là nốt." },
  { id: "go-17", game: "go", title: "Chạy nhóm hai quân", difficulty: 2, theme: "Sống chết",
    setup: { moves: [g(3, 3), g(2, 3), g(3, 4), g(2, 4), g(0, 0), g(4, 3), g(0, 1), g(4, 4), g(0, 2), g(3, 5)] },
    solution: [g(3, 2)], hint: "Nhóm đen bị vây — khí duy nhất nằm bên trái.",
    explain: "Nối ra (3,2) vừa chạy atari vừa mở thêm hai khí mới — nhóm tạm thời an toàn." },
  { id: "go-18", game: "go", title: "Thang dồn vào biên", difficulty: 3, theme: "Thang",
    setup: { moves: [g(7, 2), g(8, 2), g(8, 3), g(0, 0), g(7, 1), g(0, 1), g(9, 1), g(0, 2)] },
    solution: [g(9, 2), g(8, 1), g(8, 0)],
    hint: "Atari trước — trắng chạy thì cứ thế ép tới biên.",
    explain: "Đen atari, trắng buộc chạy (8,1) nhưng vẫn còn một khí duy nhất là biên — đen bít nốt (8,0) bắt cả nhóm. Thang luôn kết thúc ở biên hoặc chỗ có quân đỡ." },
  { id: "go-19", game: "go", title: "Thang qua giữa bàn", difficulty: 3, theme: "Thang",
    setup: { moves: [g(9, 4), g(10, 4), g(10, 3), g(0, 0), g(9, 5), g(0, 1), g(11, 5), g(0, 2)] },
    solution: [g(11, 4), g(10, 5), g(10, 6)],
    hint: "Atari từ dưới — trắng chạy ngang sẽ hết khí ngay.",
    explain: "Mỗi lần trắng chạy chỉ còn đúng một khí phía trước — đen đi trước bít nốt. Đọc thang trước khi đánh: nếu phía trước có quân đỡ, thang sẽ gãy." },
  { id: "go-20", game: "go", title: "Chạy atari hai nhịp", difficulty: 3, theme: "Sống chết",
    setup: { moves: [g(6, 6), g(5, 6), g(0, 0), g(6, 5), g(0, 1), g(6, 7), g(0, 2), g(7, 5)] },
    solution: [g(7, 6), g(8, 6), g(7, 7)],
    hint: "Bị atari liên tục — chạy theo hướng còn rộng khí.",
    explain: "Đen chạy xuống, trắng đuổi tiếp tạo atari lần hai — đen ngoặt sang (7,7) mở thêm khí. Chạy atari phải chọn hướng mở được nhiều khí nhất." },
  { id: "go-21", game: "go", title: "Bắt lưới không lối thoát", difficulty: 3, theme: "Bắt quân",
    setup: { moves: [g(8, 9), g(9, 9), g(9, 10), g(0, 0), g(10, 10), g(0, 1), g(11, 9), g(0, 2)] },
    solution: [g(9, 8), g(10, 9), g(10, 8)],
    hint: "Atari quân trắng — đường chạy của nó đi vào đúng lưới đen.",
    explain: "Đen atari, trắng chạy xuống đúng chỗ bị quân đen bao sẵn — vẫn chỉ một khí, đen bắt gọn. Đây là 'bắt lưới': trông như chạy được nhưng đường đã bị chặn." },
  { id: "go-22", game: "go", title: "Atari đôi một nước", difficulty: 3, theme: "Bắt quân",
    setup: { moves: [g(8, 9), g(9, 9), g(10, 9), g(9, 11), g(8, 11), g(0, 0), g(10, 11), g(0, 1)] },
    solution: [g(9, 10), g(9, 12), g(9, 8)],
    hint: "Ô giữa hai nhóm trắng — đánh vào đó là hai nhóm cùng bị atari.",
    explain: "(9,10) là khí chung của hai nhóm trắng — đen đánh vào thành atari đôi. Trắng chỉ cứu được một bên, đen ăn bên còn lại." },
  { id: "go-23", game: "go", title: "Chạy dọc biên trên", difficulty: 3, theme: "Sống chết",
    setup: { moves: [g(0, 3), g(0, 2), g(0, 4), g(1, 3), g(9, 9), g(1, 4)] },
    solution: [g(0, 5)], hint: "Nhóm đen biên trên bị atari — kéo dài dọc biên.",
    explain: "Ở biên chỉ còn một hướng chạy — nối (0,5) vừa thêm khí vừa tiến về phía rộng. Chạy vào góc là chết, chạy ra giữa mới sống." },
  { id: "go-24", game: "go", title: "Ăn ko — cấm ăn lại", difficulty: 2, theme: "Ko",
    setup: { moves: [g(4, 5), g(5, 5), g(6, 5), g(4, 6), g(5, 4), g(6, 6), g(0, 0), g(5, 7)] },
    solution: [g(5, 6)], hint: "Bắt quân trắng ở giữa — trắng không được ăn lại ngay.",
    explain: "Đen bắt một quân, ô vừa mất trở thành 'ko': trắng phải đi chỗ khác trước mới được ăn lại — luật ko chống lặp lại vô hạn." },
  { id: "go-25", game: "go", title: "Nới rộng lưới bắt ba", difficulty: 3, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(9, 11), g(10, 11), g(10, 9), g(0, 0), g(11, 10), g(0, 1), g(11, 12), g(0, 2)] },
    solution: [g(10, 12), g(11, 11), g(12, 11)],
    hint: "Atari trước — trắng chạy xuống cũng chỉ còn một khí.",
    explain: "Đen atari, trắng nối thêm quân nhưng nhóm lớn hơn vẫn chỉ một khí — đen bắt cả ba. Đôi khi cứ chạy càng thêm quân bị bắt." },
];
