import type { Puzzle } from "./types";

const N = 15;
const c = (r: number, col: number) => r * N + col;
const x = (r: number, col: number) => r * 9 + col;
const g = (r: number, col: number) => r * 19 + col;

export const PUZZLES: Puzzle[] = [
  /* ============ CARO — X đi trước, tìm nước mấu chốt ============ */
  { id: "caro-1", game: "caro", title: "Năm quân một đường", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(7, 8)], hint: "Hàng ngang của X sắp đủ 5.",
    explain: "Bốn quân X liền nhau, đầu còn trống — đặt quân thứ 5 là thắng ngay, O không kịp làm gì khác." },
  { id: "caro-2", game: "caro", title: "Đường chéo ẩn", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(4, 4), c(0, 0), c(5, 5), c(0, 1), c(6, 6), c(0, 2), c(7, 7), c(0, 3)] },
    solution: [c(8, 8)], hint: "Nhìn đường chéo xuôi từ góc trên.",
    explain: "Bốn quân nằm chéo từ (4,4) tới (7,7) — kéo dài bằng (8,8) là đủ 5 theo đường chéo." },
  { id: "caro-3", game: "caro", title: "Chặn trước khi muộn", difficulty: 2, theme: "Phòng thủ",
    setup: { moves: [c(3, 3), c(8, 4), c(3, 4), c(8, 5), c(3, 5), c(8, 6), c(3, 6), c(5, 10), c(10, 10)] },
    solution: [c(8, 3)], hint: "O có 4 quân hàng 9 — chặn đầu còn trống mở.",
    explain: "O có 4 quân liền, đầu phải đã bị X bịt — chỉ còn đầu (8,3). Không chặn ngay, nước sau O thắng." },
  { id: "caro-4", game: "caro", title: "Bốn mở hai đầu", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(6, 4), c(0, 0), c(6, 5), c(0, 1), c(6, 6), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(6, 3)], hint: "X có 4 quân hàng 7 — nối đủ 5 là thắng.",
    explain: "Bốn quân hai đầu mở là thế thắng chắc: nối đầu nào cũng được, O chặn một đầu thì đánh đầu kia." },
  { id: "caro-5", game: "caro", title: "Chặn đúng một đầu", difficulty: 1, theme: "Phòng thủ",
    setup: { moves: [c(0, 0), c(8, 3), c(0, 1), c(8, 4), c(0, 2), c(8, 5), c(8, 7), c(8, 6)] },
    solution: [c(8, 2)], hint: "O có 4 quân, đầu phải đã bị X bịt — chỉ còn một đầu sống.",
    explain: "O đã để 4 quân với một đầu bị X chiếm — chỉ cần chặn đầu (8,2), hàng 5 của O chết hẳn." },
  { id: "caro-6", game: "caro", title: "Chéo lên phải", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(9, 3), c(0, 0), c(8, 4), c(0, 1), c(7, 5), c(0, 2), c(6, 6), c(0, 3)] },
    solution: [c(5, 7)], hint: "Đường chéo đi lên từ trái dưới.",
    explain: "Bốn quân X bậc thang đi lên từ trái dưới — ô (5,7) kéo dài đường chéo lên đủ 5." },
  { id: "caro-7", game: "caro", title: "Ba đôi ngang dọc", difficulty: 2, theme: "Nước đôi",
    setup: { moves: [c(7, 5), c(0, 0), c(7, 6), c(0, 1), c(5, 7), c(0, 2), c(6, 7), c(0, 3)] },
    solution: [c(7, 7)], hint: "Một nước tạo hai hàng ba mở — O không chặn xuể.",
    explain: "(7,7) nối hàng ngang 5-6-7 thành mở 3, đồng thời nối dọc 5-6-7 thành mở 3 thứ hai. O chặn được một, mất hướng kia." },
  { id: "caro-8", game: "caro", title: "Phá ba đôi của đối thủ", difficulty: 2, theme: "Phòng thủ",
    setup: { moves: [c(0, 0), c(7, 5), c(0, 1), c(7, 6), c(0, 2), c(5, 7), c(0, 3), c(6, 7)] },
    solution: [c(7, 7)], hint: "O sắp đặt (7,7) tạo ba đôi — X chiếm trước giao điểm đó.",
    explain: "(7,7) là giao điểm O sẽ tạo nước đôi — chiếm trước một ô mà phá hai mối đe dọa cùng lúc." },
  { id: "caro-9", game: "caro", title: "Thắng cột dọc", difficulty: 1, theme: "Tấn công",
    setup: { moves: [c(3, 7), c(2, 7), c(4, 7), c(0, 0), c(5, 7), c(0, 1), c(6, 7), c(0, 2)] },
    solution: [c(7, 7)], hint: "Đầu trên đã bị O bịt — còn đầu dưới.",
    explain: "X có 4 quân dọc cột 8, đầu trên bị O chặn — nối đầu dưới (7,7) là đủ 5 với một đầu mở." },
  { id: "caro-10", game: "caro", title: "Ba đôi chéo ngang", difficulty: 2, theme: "Nước đôi",
    setup: { moves: [c(5, 5), c(0, 0), c(6, 6), c(0, 1), c(7, 5), c(0, 2), c(7, 6), c(0, 3)] },
    solution: [c(7, 7)], hint: "Giao điểm (7,7) nối được cả đường chéo lẫn hàng ngang.",
    explain: "(7,7) cùng lúc nối chéo 5-6-7 và ngang 5-6-7 — hai mở 3 cắt nhau tại một điểm, O chặn xuể đâu." },
  { id: "caro-11", game: "caro", title: "Nước đôi — hai mở ba", difficulty: 3, theme: "Nước đôi",
    setup: { moves: [c(7, 4), c(0, 0), c(7, 5), c(0, 1), c(6, 5), c(0, 2), c(8, 7), c(14, 14)] },
    solution: [c(7, 6), c(7, 3), c(5, 4), c(4, 3), c(9, 8)],
    hint: "Tìm ô mà X đánh vào sẽ có MỘT hàng ngang 3 và MỘT đường chéo 3 cùng mở hai đầu.",
    explain: "Nước (7,6) tạo mở 3 ngang và mở 3 chéo cùng lúc. O chặn ngang thì X bóp chéo thành mở 4 sống; O chặn đầu kia thì thắng đầu này. Người thua không phải do đi chậm — do đuổi theo hai mối đe dọa chỉ với một quân mỗi lượt." },

  /* ============ CỜ VUA ============ */
  { id: "chess-1", game: "chess", title: "Chiếu hết hàng cuối", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/4Q1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Vua đen không có ô thoát — đưa hậu xuống đáy.",
    explain: "Qe8# — ba tốt đen tự chặn đường vua, hàng cuối trống hoàn toàn. Đây là dạng chiếu hết cơ bản nhất." },
  { id: "chess-2", game: "chess", title: "Bẫy học trò", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "r1bqkbnr/pppp1ppp/2n5/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1" },
    solution: [{ from: "h5", to: "f7" }], hint: "Hậu + tượng cùng nhắm f7 — tốt yếu nhất bàn cờ.",
    explain: "Qxf7# — bẫy Scholar 2 nước: hậu h5 và tượng c4 cùng chỉa vào f7, vua đen không có ai che." },
  { id: "chess-3", game: "chess", title: "Xe chiếu hết hàng cuối", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Đưa xe xuống hàng 8 — vua đen kẹt sau 3 tốt.",
    explain: "Rb8# — xe một mình cũng đủ kết liễu khi hàng cuối bị chính tốt địch chặn đường thoát." },
  { id: "chess-4", game: "chess", title: "Hai xe soi hàng", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "7k/R7/8/8/8/8/8/1R5K w - - 0 1" },
    solution: [{ from: "b1", to: "b8" }], hint: "Xe a7 đã khóa hàng 7 — xe còn lại đặt hàng 8.",
    explain: "Rb8# — 'thang xe': một xe khóa hàng, xe kia kết liễu. Vua bị nhốt giữa hai hàng chiếu liên tục." },
  { id: "chess-5", game: "chess", title: "Xe ăn xe rồi hết", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "4r1k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e8" }], hint: "Ăn xe e8 — chiếu hết luôn vì hàng 8 không ai thủ.",
    explain: "Rxe8# — xe đen gác hàng cuối nhưng không được xe thứ hai bảo vệ: ăn ngay và chiếu hết." },
  { id: "chess-6", game: "chess", title: "Nĩa mã vua và hậu", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "6k1/8/8/3q4/4N3/8/8/4K3 w - - 0 1" },
    solution: [{ from: "e4", to: "f6" }], hint: "Mã f6 chiếu vua g8, đồng thời treo hậu d5.",
    explain: "Nf6+ là nước nĩa: vua phải chạy, mã ăn hậu nước sau. Mã nhảy qua quân nên không thể bị chặn." },
  { id: "chess-7", game: "chess", title: "Skewer bắt hậu", difficulty: 2, theme: "Chiến thuật",
    setup: { fen: "4k3/4q3/8/8/8/8/8/4R1K1 w - - 0 1" },
    solution: [{ from: "e1", to: "e7" }], hint: "Xe ăn hậu e7 chiếu — vua phải đổi xe cho hậu.",
    explain: "Rxe7+ xiên vua-hậu: vua đứng sau hậu trên cùng cột, chạy thì xe ăn hậu — đổi xe 5 điểm lấy hậu 9 điểm." },
  { id: "chess-8", game: "chess", title: "Hậu c8 kết liễu", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5ppp/8/8/8/7Q/6PP/6K1 w - - 0 1" },
    solution: [{ from: "h3", to: "c8" }], hint: "Hậu xuống hàng 8 — vua bị chính tốt mình chặn.",
    explain: "Qc8# — đường chéo h3-c8 mở sạch, vua đen không có ô thoát vì ba tốt d hàng cuối." },
  { id: "chess-9", game: "chess", title: "Ăn hậu giữa bàn", difficulty: 1, theme: "Chiến thuật",
    setup: { fen: "4k3/8/8/8/8/8/3q4/3R1K2 w - - 0 1" },
    solution: [{ from: "d1", to: "d2" }], hint: "Hậu đen d2 không ai giữ — xe đứng cạnh ăn ngay.",
    explain: "Rxd2 — hậu đen đang treo: đứng cạnh xe trắng mà không có quân nào bảo vệ. Nhìn quân 'treo' trước mỗi nước." },
  { id: "chess-10", game: "chess", title: "Hậu g7 sát", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/5p1p/7P/8/8/8/1Q4P1/6K1 w - - 0 1" },
    solution: [{ from: "b2", to: "g7" }], hint: "Đường chéo b2–g7 mở sẵn; tốt h6 đỡ hậu trên g7.",
    explain: "Qxg7# — hậu ăn tốt g7, chiếu hàng cuối; tốt trắng h6 che ô thoát h7. Vua bị gông giữa hai cánh." },
  { id: "chess-11", game: "chess", title: "Tượng bắt xe tự do", difficulty: 1, theme: "Chiến thuật",
    setup: { fen: "4k3/8/8/8/3r4/8/8/4K1B1 w - - 0 1" },
    solution: [{ from: "g1", to: "d4" }], hint: "Xe d4 không ai giữ — đường chéo g1–d4 trống.",
    explain: "Bxd4 — xe đen đứng trên đường chéo tượng mà không có quân kề bên bảo vệ: ăn thẳng." },
  { id: "chess-12", game: "chess", title: "Hậu hi sinh — gông vua", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "5r1k/6pp/7N/8/2Q5/8/8/7K w - - 0 1" },
    solution: [{ from: "c4", to: "g8" }, { from: "f8", to: "g8" }, { from: "h6", to: "f7" }],
    hint: "Nước 1: hậu nhảy vào g8 — ngay cạnh vua. Mã h6 đang bảo vệ ô đó. Đen buộc phải dùng xe ăn hậu.",
    explain: "Chiếu bí Philidor: Qg8+ hi sinh hậu; xe đen buộc phải ăn (Rxg8), và Nf7# kết liễu — vua bị chính xe và hai tốt của mình gông kín, mã không thể bị bắt vì nhảy qua." },
  { id: "chess-13", game: "chess", title: "Phong cấp kết liễu", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "6k1/4Pppp/8/8/8/8/5PPP/6K1 w - - 0 1" },
    solution: [{ from: "e7", to: "e8", promotion: "q" }], hint: "Tốt e7 chỉ còn một bước — phong hậu ngay ở ô e8.",
    explain: "e8=Q# — phong cấp và chiếu hết trong cùng một nước: hàng cuối trống, ba tốt đen chặn kín đường vua. Phong xe (e8=R) cũng hết — cứ phong hậu theo thói quen." },

  /* ============ CỜ TƯỚNG — đỏ đi trước ============ */
  { id: "xq-1", game: "xiangqi", title: "Pháo ăn mã đầu ván", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [] },
    solution: [{ from: x(7, 1), to: x(0, 1) }], hint: "Pháo đỏ (7,1) nhảy qua ngòi pháo đen (2,1) để ăn mã.",
    explain: "Pháo chỉ ăn được qua đúng một ngòi — pháo đen (2,1) chính là ngòi sẵn cho phép pháo đỏ ăn mã (0,1)." },
  { id: "xq-2", game: "xiangqi", title: "Pháo trung lộ ăn tốt", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [{ from: x(7, 1), to: x(7, 4) }, { from: x(0, 1), to: x(2, 2) }] },
    solution: [{ from: x(7, 4), to: x(3, 4) }], hint: "Tốt đỏ (6,4) là ngòi — pháo ăn tốt đen giữa sông.",
    explain: "Pháo vào trung lộ phối hợp với tốt đỏ (6,4) làm ngòi: ăn tốt đen (4,4) và uy hiếp trực tiếp cung tướng." },
  { id: "xq-3", game: "xiangqi", title: "Xe đâm thẳng bắt tướng", difficulty: 1, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/9/9/4R4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 4), to: x(0, 4) }], hint: "Cột giữa trống hoàn toàn — xe lên tận bắt tướng.",
    explain: "Xe mạnh nhất khi đường mở: cột giữa trống, xe lao thẳng tới tướng đen không ai chặn." },
  { id: "xq-4", game: "xiangqi", title: "Mã nhảy chiếu hết", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/9/9/2H6/4R4/9/9/9/4G4 r" },
    solution: [{ from: x(4, 2), to: x(2, 3) }], hint: "Mã (2,3) chiếu — tướng kẹt giữa hai sĩ, ô (1,4) đã bị xe (5,4) khóa.",
    explain: "Mã nhảy (2,3) chiếu tướng. Tướng không chạy được vì xe đỏ (5,4) kiểm soát ô (1,4) — mã chiếu luôn đi kèm một quân khóa đường thoát." },
  { id: "xq-5", game: "xiangqi", title: "Pháo bắn xe qua ngòi", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "r2aga3/9/p8/9/9/C8/9/9/9/3G5 r" },
    solution: [{ from: x(5, 0), to: x(0, 0) }], hint: "Chỉ đúng một quân cản giữa — ngòi pháo hoàn hảo.",
    explain: "Pháo ăn xe (0,0) nhờ ngòi tốt đen (2,0): giữa pháo và xe có đúng một quân là đủ." },
  { id: "xq-6", game: "xiangqi", title: "Mã tẩu ăn pháo", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "3aga3/9/9/9/2c6/9/1H7/9/9/3G5 r" },
    solution: [{ from: x(6, 1), to: x(4, 2) }], hint: "Chân mã (5,1) trống — nhảy lên ăn pháo.",
    explain: "Mã bị chặn chân thì vô dụng, chân trống thì nguy hiểm: mã (6,1) nhảy ăn pháo (4,2) vì ô (5,1) trống." },
  { id: "xq-7", game: "xiangqi", title: "Tốt qua sông ăn mã", difficulty: 1, theme: "Bắt quân",
    setup: { fen: "3aga3/9/9/9/3Ph4/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 3), to: x(4, 4) }], hint: "Tốt đã qua sông được đi ngang — ăn mã ngay.",
    explain: "Qua sông tốt 'lột xác': được đi ngang. Tốt (4,3) ngang sang ăn mã (4,4) — giá trị tốt tăng gấp bội sau sông." },
  { id: "xq-8", game: "xiangqi", title: "Xe ăn sĩ phá cung", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/3R5/9/9/9/9/9/9/9/3G5 r" },
    solution: [{ from: x(1, 3), to: x(0, 3) }], hint: "Ăn sĩ (0,3) — mở mặt tướng và chiếu luôn.",
    explain: "Rxa0+ vừa ăn sĩ vừa chiếu: sĩ là tường thành cung — đổi xe lấy sĩ khi xe còn hoạt động là nước thắng thế, lộ mặt tướng là mầm họa." },
  { id: "xq-9", game: "xiangqi", title: "Tốt độc phá sát", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/4P4/9/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(1, 4), to: x(0, 4) }], hint: "Tốt lao xuống bắt tướng — sĩ không cứu được.",
    explain: "Tốt sát cung là pháo đài sống: lao xuống (0,4) ép tướng đổi chỗ, còn tốt thì đeo bám không rời. Một tốt trong cung đáng bằng xe ngoài biên." },
  { id: "xq-10", game: "xiangqi", title: "Mã góc pháo bộ", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/9/5H3/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 5), to: x(0, 4) }], hint: "Mã (2,5) nhảy góc (0,4) — chân mã (1,5) trống.",
    explain: "Mã nhảy góc cung là đòn kết liễu kinh điển: từ (2,5) tới (0,4), tướng bị nhốt giữa các sĩ không có ô thoát." },
  { id: "xq-11", game: "xiangqi", title: "Pháo yểm trung lộ", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "3aga3/3ppp3/9/9/9/3C5/9/9/9/4G4 r" },
    solution: [{ from: x(5, 3), to: x(5, 4) }], hint: "Đen đã tự khóa kín năm ô thoát của tướng. Pháo chỉ cần vào cột giữa — nhớ ngòi.",
    explain: "Năm ô chạy của tướng bị chính sĩ và tốt đen chôn kín. Pháo vào (5,4) là chiếu và đen không gỡ được: chặn cột thì pháo ăn qua ngòi tốt (1,4), chạy thì hết đường. Bài học: cung đối thủ tự đóng khóa chính là đòn pháo trung." },
  { id: "xq-12", game: "xiangqi", title: "Song xe nhốt cung", difficulty: 2, theme: "Chiếu hết",
    setup: { fen: "4ga3/8R/R3e4/9/9/9/9/9/9/4G4 r" },
    solution: [{ from: x(2, 0), to: x(0, 0) }], hint: "Một xe khóa hàng 1, xe còn lại chiếu hàng 0 — tướng bị nhốt giữa hai 'tường'.",
    explain: "Xe (1,8) khóa hết hàng 1, xe (0,0) chiếu xuyên hàng 0. Hai xe tàn cuộc là cặp sát thủ: luôn kết liễu bằng cách bó vua vào biên rồi chiếu hàng." },
  { id: "xq-13", game: "xiangqi", title: "Mã đe đôi", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "3aga3/r1c6/4p4/9/9/H8/9/9/9/4G4 r" },
    solution: [{ from: x(5, 0), to: x(3, 1) }, { from: x(1, 0), to: x(2, 0) }, { from: x(3, 1), to: x(1, 2) }],
    hint: "Mã nhảy lên (3,1): nhìn xem nó đang chĩa vào những quân đen nào cùng lúc?",
    explain: "Mã (3,1) đe đôi xe (1,0) và pháo (1,2). Đen phải cứu xe (quân mạnh hơn), mã ung dung ăn pháo nước sau — đòn đe đôi của mã luôn thắng vì mã nhảy qua, không chặn được." },
  { id: "xq-14", game: "xiangqi", title: "Mã đè sĩ", difficulty: 3, theme: "Chiếu hết",
    setup: { fen: "3aga3/R8/4c4/9/2H6/9/9/9/9/4G4 r" },
    solution: [{ from: x(4, 2), to: x(2, 3) }], hint: "Xe (1,0) đã khóa hàng 1. Mã chỉ cần một điểm nhảy trống chân mà chiếu được tướng.",
    explain: "Xe (1,0) soi cả hàng 1, mã (2,3) chiếu tướng qua ô chân (1,3) trống. Pháo đen (2,4) không thể ăn mã vì kề nhau không ngòi — 'mã đè sĩ' là dạng chiếu hết kinh điển: xe khóa đường, mã kết liễu." },
  { id: "xq-15", game: "xiangqi", title: "Xe buộc pháo, xuyên hàng bắt mã", difficulty: 2, theme: "Bắt quân",
    setup: { fen: "4g4/9/9/h3c4/9/7R1/9/9/9/4G4 r" },
    solution: [{ from: x(5, 7), to: x(3, 7) }, { from: x(3, 4), to: x(2, 4) }, { from: x(3, 7), to: x(3, 0) }],
    hint: "Xe xuống (3,7) đe pháo. Pháo chạy thì hàng 3 trống — xe muốn ăn ai?",
    explain: "Xe (3,7) đe pháo buộc đen phải bê pháo khỏi hàng 3 — và hàng 3 vừa trống chính là xa lộ xe lao tới bắt mã (3,0). Đe một quân để mở đường ăn quân khác: cách 'đi mòn' xe kinh điển." },

  /* ============ CỜ VÂY — đen đi trước, bắt quân ============ */
  { id: "go-1", game: "go", title: "Bắt quân đầu tiên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(10, 9), g(0, 0), g(11, 10), g(0, 1)] },
    solution: [g(10, 11)], hint: "Trắng (10,10) chỉ còn 1 khí.",
    explain: "Quân trắng chỉ còn đúng một khí (10,11) — lấp khí cuối là bắt, quân bị nhấc khỏi bàn." },
  { id: "go-2", game: "go", title: "Bắt nhóm hai quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(10, 9), g(8, 9), g(10, 10), g(9, 8), g(0, 0), g(11, 9), g(0, 1), g(10, 8), g(0, 2), g(11, 10), g(0, 3), g(9, 10), g(0, 4)] },
    solution: [g(10, 11)], hint: "Nhóm trắng (10,9)-(10,10) chỉ còn đúng 1 khí — bít nốt.",
    explain: "Nhóm liền nhau chia sẻ khí — bít khí cuối của CẢ NHÓM thì cả nhóm bị bắt cùng lúc." },
  { id: "go-3", game: "go", title: "Bắt quân góc bàn", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 0), g(0, 1), g(9, 8)] },
    solution: [g(1, 0)], hint: "Ở góc chỉ còn một khí (1,0).",
    explain: "Góc bàn chỉ có 2 khí (đất là tường) — quân góc yếu nhất, bắt dễ nhất." },
  { id: "go-4", game: "go", title: "Bắt nhóm ba quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(4, 7), g(5, 7), g(6, 5), g(0, 0), g(6, 6), g(0, 1), g(6, 7), g(0, 2), g(5, 4), g(0, 3)] },
    solution: [g(5, 8)], hint: "Nhóm trắng hàng 5 bị vây — chỉ còn khí (5,8).",
    explain: "Nhóm ba quân chia sẻ đúng một khí cuối — bít (5,8) là nhấc cả nhóm. Đếm khí nhóm, đừng đếm từng quân." },
  { id: "go-5", game: "go", title: "Bít khí cuối cùng", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(7, 8), g(8, 8), g(7, 9), g(8, 9), g(8, 10), g(9, 8), g(9, 7), g(0, 0), g(8, 7), g(0, 1)] },
    solution: [g(9, 9)], hint: "Nhóm trắng 3 quân chỉ còn khí (9,9).",
    explain: "Trước khi đánh, luôn đếm khí của nhóm bị vây: (9,9) là khí duy nhất còn lại của nhóm trắng." },
  { id: "go-6", game: "go", title: "Ăn quân trên biên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 5), g(0, 4), g(9, 8), g(0, 6), g(9, 7)] },
    solution: [g(1, 5)], hint: "Quân biên trên chỉ còn khí (1,5).",
    explain: "Quân biên ít khí hơn giữa bàn — ở biên chỉ cần 3 quân là nhốt, ở giữa cần 4." },
  { id: "go-7", game: "go", title: "Vây nhóm hai quân", difficulty: 2, theme: "Bắt quân",
    setup: { moves: [g(9, 10), g(10, 10), g(9, 11), g(10, 11), g(11, 10), g(0, 0), g(11, 11), g(0, 1), g(10, 9), g(0, 2)] },
    solution: [g(10, 12)], hint: "Nhóm trắng chỉ còn khí bên phải.",
    explain: "Nhóm trắng (10,10)-(10,11) đã bị bao 3 phía — khí cuối (10,12) là chỗ dựa duy nhất của nó." },
  { id: "go-8", game: "go", title: "Nối quân thoát vây", difficulty: 2, theme: "Sống chết",
    setup: { moves: [g(0, 0), g(4, 5), g(5, 5), g(4, 6), g(5, 6), g(6, 5), g(0, 1), g(6, 6), g(0, 2), g(5, 7)] },
    solution: [g(5, 4)], hint: "Nhóm đen bị đe atari — chạy ra (5,4) để thêm khí.",
    explain: "Atari (còn 1 khí) phải chạy ngay: (5,4) nối thêm quân và mở khí mới. Để atari không chạy là mất quân chỉ vì quên đếm." },
  { id: "go-9", game: "go", title: "Bắt ba quân góc", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(0, 0), g(0, 2), g(0, 1), g(2, 0), g(1, 0)] },
    solution: [g(1, 1)], hint: "Nhóm trắng góc chỉ còn khí (1,1).",
    explain: "Nhóm 3 quân ở góc có tối đa 6 khí nhưng bị bao kín chỉ còn (1,1) — góc là nơi dễ bắt nhất bàn cờ." },
  { id: "go-10", game: "go", title: "Atari quân chạy biên", difficulty: 1, theme: "Bắt quân",
    setup: { moves: [g(9, 9), g(3, 0), g(2, 0), g(9, 8), g(4, 0), g(9, 7)] },
    solution: [g(3, 1)], hint: "Quân trắng biên trái chỉ còn khí (3,1).",
    explain: "Quân chạy dọc biên rất đuối khí: mỗi bước chỉ mở được 2-3 khí. Đánh vào (3,1) là atari — quân trắng phải chạy dài hoặc chết." },
];
